# Generated by Django 4.1.7 on 2023-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_product_fabriquant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info_produit',
            field=models.TextField(blank=True),
        ),
    ]
