# Generated by Django 4.1.7 on 2023-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='caption',
            new_name='texte',
        ),
    ]
