# Generated by Django 4.1.7 on 2023-03-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productimage_delete_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
