# Generated by Django 4.1.7 on 2023-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='products/%Y/%m%d'),
        ),
    ]
