# Generated by Django 4.1.7 on 2023-03-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='products/%Y/%m%d'),
        ),
    ]
